User.create(name: "MitsunChieh", address: "10048臺北市中正區重慶南路1段122號")
Chef.create(name: "AnthonyLiu")
Ingredient.create(name: "飯")
Ingredient.create(name: "牛肉")
Ingredient.create(name: "洋蔥")
Ingredient.create(name: "蛋")
Ingredient.create(name: "義大利麵")
Ingredient.create(name: "韭黃")
Ingredient.create(name: "番茄")
Ingredient.create(name: "蝦仁")
Recipe.create(name: "主廚推薦",
              description: "吃我的姚明啦～")
Recipe.create(name: "壽喜燒牛丼飯",
              description: "喜歡吃日式料理中的牛丼嗎？快速的動手做吧～",
              flavor: "日式",
              ingredient: "牛肉,洋蔥,飯",
              content: "/images/recipe_images/壽喜燒牛丼飯.jpg")
Recipe.create(name: "蔬菜牛肉湯",
              description: "餐廳內常喝到的牛肉蔬菜湯，動手自己做吧～",
              flavor: "中式",
              ingredient: "番茄,高麗菜,牛肉",
              content: "/images/recipe_images/蔬菜牛肉湯.jpg")
Recipe.create(name: "義大利肉醬麵餐盒",
              flavor: "義式",
              ingredient: "義大利麵,豬肉,番茄",
              content: "/images/recipe_images/義大利肉醬麵餐盒.jpg")
Recipe.create(name: "茄汁燉飯",
              flavor: "中式",
              ingredient: "飯,番茄,洋蔥",
              content: "/images/recipe_images/茄汁燉飯.jpg")
Recipe.create(name: "蝦仁蛋包飯",
              flavor: "日式",
              ingredient: "飯,蝦仁,蛋",
              content: "/images/recipe_images/蝦仁蛋包飯.jpg")
Recipe.create(name: "滑蛋蝦仁燴飯",
              flavor: "港式",
              ingredient: "飯,蝦仁,蛋",
              content: "/images/recipe_images/滑蛋蝦仁燴飯.jpg")
Recipe.create(name: "蒜頭蒸蛋",
              flavor: "中式",
              ingredient: "蛋,大蒜",
              content: "/images/recipe_images/蒜頭蒸蛋.jpg")
Recipe.create(name: "韭黃炒牛肉絲",
              flavor: "中式",
              ingredient: "韭黃,牛肉",
              content: "/images/recipe_images/韭黃炒牛肉絲.jpg")
Recipe.create(name: "蕃茄海鮮義大利麵",
              flavor: "義式",
              ingredient: "番茄,蝦仁,義大利麵",
              content: "/images/recipe_images/蕃茄海鮮義大利麵.jpg")
Recipe.create(name: "韭黃牛肉餛飩餡",
              flavor: "中式",
              ingredient: "韭黃,牛肉,麵粉",
              content: "/images/recipe_images/韭黃牛肉餛飩餡.jpg")

