User.create(name: 'MitsunChieh')
Chef.create(name: 'AnthonyLiu')
Ingredient.create(name: '雞')
Ingredient.create(name: '義大利麵')
Ingredient.create(name: '奶油')
Ingredient.create(name: '蛋')
Ingredient.create(name: '麵粉')
Ingredient.create(name: '柳橙')